# Generated by Django 5.2.7 on 2025-12-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statiysate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('bit', 'Быт'), ('studies', 'Учеба'), ('work', 'Работа'), ('food', 'Еда'), ('emergency', 'ЧП'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Категория'),
        ),
    ]
