# Generated by Django 5.2.7 on 2025-10-21 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statiysate', '0002_user_remove_article_updated_at_article_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
    ]
