# Generated by Django 5.2.7 on 2025-11-11 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statiysate', '0003_remove_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='statiysate.user', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.TextField(max_length=400, verbose_name='Краткое описание'),
        ),
    ]
