# Generated by Django 5.2.7 on 2025-11-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statiysate', '0004_article_user_alter_article_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('tech', 'Технологии'), ('sport', 'Спорт'), ('news', 'Новости'), ('art', 'Искусство'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Категория'),
        ),
    ]
